splash = false

wallpaper {
    monitor = LVDS-1
    path = /home/leif/Pictures/wallpaper.png
    fit_mode = cover
}

# optionaler Fallback für alle anderen / neue Monitore
wallpaper {
    monitor =
    path = /home/leif/Pictures/wallpaper.png
    fit_mode = cover
}
